# Generated by Django 4.0.6 on 2022-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.TextField(null=True)),
            ],
        ),
    ]
