# Generated by Django 3.2.3 on 2022-07-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
